# Generated by Django 5.1.1 on 2024-09-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_auto_20230612_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
